### ISSUE TITLE
Main_Page!

### ISSUE THREAD

**Issue by thomas-touhey** [samshadwell/Clicks2Hitler#2]
So the `Main_Page` appears in my result, and that's not funny! Please fix this (when you can) :)

	['https://en.wikipedia.org/wiki/Jumper', 'http://en.wikipedia.org/wiki/Main_Page', 'http://en.wikipedia.org/wiki/Nazi_concentration_camps', 'http://en.wikipedia.org/wiki/Adolf_Hitler']

(btw, I'm having great fun with this, thanks :D)

**Comment by samshadwell** [comment]
Oh, man. I haven't touched this project in a couple of years. I think it should be pretty easy to filter out the main page, though.

**Comment by samshadwell** [comment]
Done! The answer you were looking for is:

 ['https://en.wikipedia.org/wiki/Jumper ', 'http://en.wikipedia.org/wiki/Parachuting', 'http://en.wikipedia.org/wiki/Rallying', 'http://en.wikipedia.org/wiki/Adolf_Hitler']

**Comment by thomas-touhey** [comment]
Yay, thanks :D
